### ISSUE TITLE
Default of stable, v.s. mainline?

### ISSUE THREAD

**Issue by kennethgillen** [openmicroscopy/ansible-role-nginx#1]
I'm curious why `stable` is the default choice?

cf https://www.nginx.com/blog/nginx-1-6-1-7-released/ - under 'which version should I use':
> We recommend that in general you deploy the NGINX mainline branch at all times

**Comment by manics** [comment]
`mainline` may contain unwanted changes in patch releases e.g. https://trello.com/c/FpU9Bz5O/90-cap-nginx-or-rebuild-nginx-cache

**Comment by kennethgillen** [comment]
Cheers @manics.
